version: '2'

services:

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes: 
      - ./volumes/mongo/config:/data/configdb
      - ./volumes/mongo/data:/data/db
    restart: always

